apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-end-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: backend.local-staging
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: back-end-service
            port:
              number: 8000
